version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - update-alternatives --auto javac
      - update-alternatives --auto java
      
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd ${CODEBUILD_SRC_DIR}/(...) && mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
      - shoppingcart.jar
